export const initialValues = {
  pageWidth: '33.0000',
  pageHeight: '52.0000',
  columnWidth: '2.9800',
  gutterSpace: '0.3500',
  paragraphSpacing: '1.0000',
  headlineFont: 'Select Font',
  headlineFontSize: '10.0000',
  headlineFontLeading: '10.0000',
  placeFont: 'Select Font',
  placeFontSize: '8.0000',
  placeFontLeading: '11.0000',
  basicStoryFont: 'Select Font',
  basicStoryFontSize: '9.5000',
  basicStoryFontLeading: '9.0000',
  photoSize: '2.9700',
  photoResolutionWidth: '244.0000',
  photoResolutionHeight: '213.0000',
  photoBgColor: 'default',
  advertisingColumnWidth: '123.0000',
  advertGutterSpace: '0.000000',
};

export const scaleByField = {
  pageWidth: 'cm',
  pageHeight: 'cm',
  columnWidth: 'cm',
  gutterSpace: 'cm',
  paragraphSpacing: 'cm',
  headlineFont: '',
  headlineFontSize: 'pt',
  headlineFontLeading: 'pt',
  placeFont: '',
  placeFontSize: 'pt',
  placeFontLeading: 'pt',
  basicStoryFont: '',
  basicStoryFontSize: 'pt',
  basicStoryFontLeading: 'pt',
  photoSize: 'cm',
  photoResolutionWidth: 'px',
  photoResolutionHeight: 'px',
  photoBgColor: '',
  advertisingColumnWidth: 'cm',
  advertGutterSpace: 'cm',
};

export const dropdownFields = ['headlineFont', 'placeFont', 'basicStoryFont'];

export const fontOptions = [
  'Select Font',
  'AarchaUB',
  'AarchaUN',
  'ChirthaHeavyUniN',
  'ChiruthaUHB',
  'PanchariUN',
  'UnniyarchaUB',
  'UnniyarchaUN',
  'Vimas-Medium',
  'VimasMed',
];

export const customLabels = {
  pageWidth: 'Page Width',
  pageHeight: 'Page Height',
  columnWidth: 'Column Width',
  gutterSpace: 'Gutter Space',
  paragraphSpacing: 'Paragraph Spacing',
  headlineFont: 'Headline Font',
  headlineFontSize: 'Headline Font Size',
  headlineFontLeading: 'Headline Font Leading',
  placeFont: 'Place Font',
  placeFontSize: 'Place Font Size',
  placeFontLeading: 'Place Font Leading',
  basicStoryFont: 'Basic Story Font',
  basicStoryFontSize: 'Basic Story Font Size',
  basicStoryFontLeading: 'Basic Story Font Leading',
  photoSize: 'Photo Size',
  photoResolutionWidth: 'Photo Resolution Width',
  photoResolutionHeight: 'Photo Resolution Height',
  photoBgColor: 'Photo Background Color',
  advertisingColumnWidth: 'Advertising Column Width',
  advertGutterSpace: 'Advert Gutter Space',
};



export const presets = {
  preset1: {
    pageWidth: '33.0000',
    pageHeight: '52.0000',
    columnWidth: '2.9800',
    gutterSpace: '0.3500',
    paragraphSpacing: '1.0000',
    advertisingColumnWidth: '123.0000',
    advertGutterSpace: '0.000000',
    headlineFont: 'AarchaUB',
    headlineFontSize: '10.0000',
    headlineFontLeading: '10.0000',
    placeFont: 'PanchariUN',
    placeFontSize: '8.0000',
    placeFontLeading: '11.0000',
    basicStoryFont: 'UnniyarchaUB',
    basicStoryFontSize: '9.5000',
    basicStoryFontLeading: '9.0000',
    photoSize: '2.9700',
    photoResolutionWidth: '244.0000',
    photoResolutionHeight: '213.0000',
    photoBgColor: 'Grey',
    status: 0,
  },
  preset2: {
    pageWidth: '0.0000',
    pageHeight: '0.0000',
    columnWidth: '0.9800',
    gutterSpace: '0.3500',
    paragraphSpacing: '0.0000',
    advertisingColumnWidth: '0.0000',
    advertGutterSpace: '0.000000',
    headlineFont: 'ChirthaHeavyUniN',
    headlineFontSize: '10.0000',
    headlineFontLeading: '10.0000',
    placeFont: 'ChiruthaUHB',
    placeFontSize: '8.0000',
    placeFontLeading: '11.0000',
    basicStoryFont: 'VimasMed',
    basicStoryFontSize: '9.5000',
    basicStoryFontLeading: '9.0000',
    photoSize: '0.9700',
    photoResolutionWidth: '0.0000',
    photoResolutionHeight: '0.0000',
    photoBgColor: 'grey',
    status: 1,
  },
  preset3: {
    pageWidth: '0.0000',
    pageHeight: '0.0000',
    columnWidth: '0.9800',
    gutterSpace: '0.3500',
    paragraphSpacing: '0.0000',
    advertisingColumnWidth: '0.0000',
    advertGutterSpace: '0.000000',
    headlineFont: 'ChirthaHeavyUniN',
    headlineFontSize: '10.0000',
    headlineFontLeading: '10.0000',
    placeFont: 'ChiruthaUHB',
    placeFontSize: '8.0000',
    placeFontLeading: '11.0000',
    basicStoryFont: 'VimasMed',
    basicStoryFontSize: '9.5000',
    basicStoryFontLeading: '9.0000',
    photoSize: '0.9700',
    photoResolutionWidth: '0.0000',
    photoResolutionHeight: '0.0000',
    photoBgColor: 'grey',
    status: 0,
  }
}
