import oommen from "./Assets/2.jpg"
import rajamma from "./Assets/17.jpg"
import sukumaran from "./Assets/20.jpg"
import devan from "./Assets/27.jpg"
import thamarakshan from "./Assets/29.jpg"

const cards = [
    {
        obitID: 1,
        photo: oommen,
        position: '3',
        unit: 'KTM',
        place: 'പുത്തൻകാവ്',
        name: 'കൃഷ്ണൻകുട്ടി പിള്ള',
        date: '02-15-2020',
        bureau: 'kottayam',
    },
    {
        obitID: 2,
        photo: rajamma,
        position: '2',
        unit: 'KTM',
        place: 'പാണ്ടങ്കരി',
        name: 'കുട്ടപ്പൻ ആചാരി',
        date: '02-07-2021',
        bureau: 'kottayam',
    },
    {
        obitID: 3,
        photo: sukumaran,
        position: '6',
        unit: 'MPM',
        place: 'ചെന്നിത്തല',
        name: 'ആർ.അജയൻ',
        date: '01-12-2023',
        bureau: 'kottayam',
    },
    {
        obitID: 4,
        photo: devan,
        position: '7',
        unit: 'KTM',
        place: 'പുളിങ്കുന്ന്',
        name: 'വിജയമ്മ',
        date: '01-12-2023',
        bureau: 'kottayam',
    },
    {
        obitID: 5,
        photo: thamarakshan,
        position: '4',
        unit: 'EKM',
        place: 'മാന്നാർ',
        name: 'ലില്ലി ചാക്കോ',
        date: '02-15-2022',
        bureau: 'kottayam',
    },
    {
        obitID: 6,
        photo: oommen,
        position: '3',
        unit: 'EKM',
        place: 'മാന്നാർ',
        name: 'രാജശേഖരൻ നായർ',
        date: '01-12-2023',
        bureau: 'kottayam',
    },
    {
        obitID: 7,
        photo: rajamma,
        position: '2',
        unit: 'ALP',
        place: 'പട്ടണക്കാട്',
        name: 'കെ.ആർ.വിശ്വനാഥപിള്ള',
        date: '01-12-2023',
        bureau: 'kottayam',
    },
    {
        obitID: 8,
        photo: oommen,
        position: '6',
        unit: 'KTM',
        place: 'വെട്ടിയാർ',
        name: 'എം.എ.മദനരാജൻ പിള്ള',
        date: '02-07-2020',
        bureau: 'kottayam',
    },
    {
        obitID: 9,
        photo: devan,
        position: '7',
        unit: 'KTM',
        place: 'പുത്തൻകാവ്',
        name: 'സുഹുറാബീവി',
        date: '01-12-2023',
        bureau: 'kottayam',
    },
    {
        obitID: 10,
        photo: thamarakshan,
        position: '4',
        unit: 'TVM',
        place: 'കല്ലിശേരി',
        name: 'ഉഷാ കുമാരി',
        date: '01-12-2023',
        bureau: 'kottayam',
    },

    {
        obitID: 11,
        photo: oommen,
        position: '3',
        unit: 'KTM',
        place: 'ചെന്നിത്തല',
        name: 'രാധമ്മ പിള്ള',
        date: '01-12-2023',
        bureau: 'kottayam',
    },
    {
        obitID: 12,
        photo: rajamma,
        position: '2',
        unit: 'PKD',
        place: 'മണ്ണഞ്ചേരി',
        name: 'സുരേന്ദ്രൻ',
        date: '02-06-2021',
        bureau: 'kottayam',
    },
    {
        obitID: 13,
        photo: sukumaran,
        position: '6',
        unit: 'KNR',
        place: 'കല്ലിശേരി',
        name: 'ശോശാമ്മ ഇടിക്കുള',
        date: '02-06-2022',
        bureau: 'kottayam',

    },
    {
        obitID: 14,
        photo: rajamma,
        position: '7',
        unit: 'EKM',
        place: 'ഹരിപ്പാട്',
        name: 'കൊച്ചുരാജൻ',
        date: '01-12-2023',
        bureau: 'kottayam',
    },
    {
        obitID: 15,
        photo: thamarakshan,
        position: '4',
        unit: 'EKM',
        place: 'അമ്പലപ്പുഴ',
        name: 'സി.പി. സുഭദ്രക്കുട്ടി',
        date: '01-12-2023',
        bureau: 'kottayam',
    },
    {
        obitID: 16,
        photo: oommen,
        position: '3',
        unit: 'ALP',
        place: 'ആലപ്പുഴ',
        name: 'ഗ്രേസി',
        date: '01-12-2023',
        bureau: 'kottayam',
    },
    {
        obitID: 17,
        photo: sukumaran,
        position: '2',
        unit: 'ALP',
        place: 'ആലപ്പുഴ',
        name: 'സുരേഷ്കുമാർ',
        date: '01-12-2023',
        bureau: 'kottayam',
    },
    {
        obitID: 18,
        photo: sukumaran,
        position: '6',
        unit: 'KTM',
        place: 'എടത്വ',
        name: 'രവീന്ദ്രപണിക്കർ',
        date: '01-12-2023',
        bureau: 'kottayam',
    },
    {
        obitID: 19,
        photo: devan,
        position: '7',
        unit: 'ALP',
        place: 'പല്ലന',
        name: 'സക്കറിയ കെ.ഫിലിപ്പ',
        date: '01-12-2023',
        bureau: 'kottayam',
    },
    {
        obitID: 20,
        photo: thamarakshan,
        position: '4',
        unit: 'EKM',
        place: 'കുറത്തികാട്',
        name: 'അന്നമ്മ വർഗീസ്',
        date: '01-12-2023',
        bureau: 'kottayam',
    },
    {
        obitID: 21,
        photo: devan,
        position: '4',
        unit: 'KTM',
        place: 'കുറുപ്പംപടി',
        name: 'ഫിലിപ് വർഗീസ്',
        date: '01-12-2023',
        bureau: 'kottayam',
    },
    {
        obitID: 22,
        photo: sukumaran,
        position: '4',
        unit: 'KTM',
        place: 'മണ്ണഞ്ചേരി',
        name: 'ഫാത്തിമ കുഞ്ഞ്',
        date: '01-12-2023',
        bureau: 'kottayam',
    },
    {
        obitID: 23,
        photo: devan,
        position: '6',
        unit: 'KTM',
        place: 'പെരുമ്പാവൂർ',
        name: 'പരമേശ്വരൻ കർത്താ',
        date: '01-12-2023',
        bureau: 'kottayam',
    },
    {
        obitID: 24,
        photo: devan,
        position: '6',
        unit: 'KTM',
        place: 'പെരുമ്പാവൂർ',
        name: 'പരമേശ്വരൻ കർത്താ',
        date: '01-12-2023',
        bureau: 'kottayam',
    },
    {
        obitID: 25,
        photo: devan,
        position: '6',
        unit: 'KTM',
        place: 'ഏഴുമാംതുരുത്ത്',
        name: 'ചെല്ലപ്പൻ',
        date: '01-12-2023',
        bureau: 'kottayam',
    }
];

export default cards;
